[about]
name = "Jonathan"
avatar = "Jonathan.jpeg"
hobbies = ["🎨 Desgin", "💻 Programming", "🏸 Badminton"]
skills = ["C#", "Rust", "TypeScript", "Vue"]

[social]
github = "djdjz7"
website = "https://djdjz7.top"
